apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-syncer-state
  namespace: rss-feed-to-instapaper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
