apiVersion: v1
kind: Secret
metadata:
  name: instapaper-credentials
  namespace: rss-feed-to-instapaper
type: Opaque
stringData:
  INSTAPAPER_USERNAME: "your-instapaper-email@example.com"
  INSTAPAPER_PASSWORD: "your-instapaper-password"
